### ISSUE TITLE
增加學習診斷的教師群

### ISSUE THREAD

**Issue by water5127** [3dw/automap#11]
目前只有宗浩老師一人，但是中文、英文、科學、家庭溝通等等都會有診斷需求。
本會資深老師涵括各領域，且都有診斷的實力，
建議邀請各老師加入診斷行列。

**Comment by bestian** [comment]
這是我在WISELIKE開的公開問答平台，已啟用
https://wiselike.com/bestian-tang
請參考看看
這應該目前找得到的最好用的公開問答平台，適合公開式網路諮詢

**Comment by water5127** [comment]
點進去的反應是 Internal Server Error

2017-03-02 12:29 GMT+08:00 Bestian Tang 唐宗浩 <notifications@github.com>:

**Comment by bestian** [comment]
對方的問題，過陣子應該就會好了
另
新增唐鳳成為諮詢志工
