### ISSUE TITLE
登錄覆蓋問題

### ISSUE THREAD

**Issue by bestian** [3dw/automap#5]
新登錄者有時會蓋掉最後登錄的人的整筆資料
估計和「scope.n」的設定錯誤有關
可能是submit函式執行時，n錯了一號
debug時可從login, submit, scope.n這三處著手

**Comment by bestian** [comment]
查到因為一筆null的資料，使length減少了1，所以才出現新人蓋舊人的問題，目前已除該筆null資料，並停 止了「移除」的功能，應該已修復成功。

**Comment by ilake** [comment]
:+1:
